extends Node2D

# This variable holds the total time in seconds
var remaining_time_in_seconds = 180

# This function is called when the scene first loads
func _ready():
	# This triggers your CutsceneManager script.
	# It will play the Animation FIRST, wait for it to end, 
	# and THEN run the extra movement code you wrote.
	$CutsceneManager.play_intro_cutscene()
	
	# Start your timer
	update_timer_label()

# This function was auto-generated by connecting the signal
func _on_timer_timeout():
	# Subtract one second
	remaining_time_in_seconds -= 1

	# Check if time ran out
	if remaining_time_in_seconds <= 0:
		$UI_Layer/Timer.stop()
		$UI_Layer/TimerLabel.text = "0:00"
		# Add code here for what happens when time is up
	else:
		# Update the label's text
		update_timer_label()

# This function formats the time to look nice
func update_timer_label():
	# This math converts total seconds into minutes and seconds
	var minutes = remaining_time_in_seconds / 60
	var seconds = remaining_time_in_seconds % 60
	
	# The "%02d" part ensures it's "0:05" instead of "0:5"
	$UI_Layer/TimerLabel.text = "%d:%02d" % [minutes, seconds]
