extends Node2D

# This variable holds the total time in seconds
var remaining_time_in_seconds = 180  # (3 minutes * 60 seconds)

# This function is called when the scene first loads
func _ready():
	# Make sure your Timer node is set to "Autostart" in the Inspector
	# Set the label's text when the game first starts
	update_timer_label()

# This function was auto-generated by connecting the signal
# It runs every 1 second (because your Timer's Wait Time is 1.0)
func _on_timer_timeout():
	# Subtract one second
	remaining_time_in_seconds -= 1

	# Check if time ran out
	if remaining_time_in_seconds <= 0:
		$UI_Layer/Timer.stop()
		$UI_Layer/TimerLabel.text = "0:00"
		
		# Add code here for what happens when time is up
		# For example, to restart the level:
		# get_tree().reload_current_scene() 
	else:
		# Update the label's text
		update_timer_label()

# This function formats the time to look nice
func update_timer_label():
	# This math converts total seconds into minutes and seconds
	var minutes = remaining_time_in_seconds / 60
	var seconds = remaining_time_in_seconds % 60
	
	# The "%02d" part ensures it's "0:05" instead of "0:5"
	# This line finds the Label node inside the UI_Layer
	$UI_Layer/TimerLabel.text = "%d:%02d" % [minutes, seconds]
